// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektPortfolio_sr1630.DAL;

#nullable disable

namespace ProjektPortfolio_sr1630.Migrations
{
    [DbContext(typeof(ProjectsContext))]
    partial class ProjectsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjektPortfolio_sr1630.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "A responsive personal portfolio website showcasing skills and projects.",
                            Name = "Personal Portfolio",
                            Pic = "https://picsum.photos/200/300?random=11",
                            Technologies = "HTML, CSS, JavaScript, Bootstrap"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "An application for task management with notifications and reporting.",
                            Name = "Task Tracker",
                            Pic = "https://picsum.photos/200/300?random=12",
                            Technologies = "C#, .NET Core, SQL Server"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "E-commerce platform for browsing and purchasing products.",
                            Name = "Online Store",
                            Pic = "https://picsum.photos/200/300?random=13",
                            Technologies = "React, Node.js, Express, MongoDB"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "A content management system for creating and managing blog posts.",
                            Name = "Blogging CMS",
                            Pic = "https://picsum.photos/200/300?random=14",
                            Technologies = "PHP, Laravel, MySQL, TailwindCSS"
                        },
                        new
                        {
                            Id = 5,
                            Desc = "A weather forecasting app using OpenWeatherMap API.",
                            Name = "Weather App",
                            Pic = "https://picsum.photos/200/300?random=15",
                            Technologies = "JavaScript, Vue.js, CSS"
                        },
                        new
                        {
                            Id = 6,
                            Desc = "A quiz system with scoring and detailed result reports.",
                            Name = "Quiz Application",
                            Pic = "https://picsum.photos/200/300?random=16",
                            Technologies = "Python, Flask, PostgreSQL"
                        },
                        new
                        {
                            Id = 7,
                            Desc = "Real-time chat application with group chat functionality.",
                            Name = "Chat Platform",
                            Pic = "https://picsum.photos/200/300?random=17",
                            Technologies = "JavaScript, Socket.IO, Node.js"
                        },
                        new
                        {
                            Id = 8,
                            Desc = "A personal finance management tool with budget planning.",
                            Name = "Expense Tracker",
                            Pic = "https://picsum.photos/200/300?random=18",
                            Technologies = "Java, Spring Boot, Hibernate, MySQL"
                        },
                        new
                        {
                            Id = 9,
                            Desc = "An app for browsing and saving cooking recipes.",
                            Name = "Recipe App",
                            Pic = "https://picsum.photos/200/300?random=19",
                            Technologies = "Kotlin, Android Studio, Firebase"
                        },
                        new
                        {
                            Id = 10,
                            Desc = "A 3D viewer application for showcasing digital artwork.",
                            Name = "3D Art Viewer",
                            Pic = "https://picsum.photos/200/300?random=20",
                            Technologies = "C#, Unity, Blender"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
